version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
configuration: Release
only_commits:
  message: /#build/
build:
  verbosity: minimal
after_build:
- cmd: 7z a PixelArtTool.zip %APPVEYOR_BUILD_FOLDER%\PixelArtTool\bin\Release\*.exe %APPVEYOR_BUILD_FOLDER%\PixelArtTool\bin\Release\*.exe.config
artifacts:
- path: PixelArtTool.zip
  name: deploy
deploy:
- provider: GitHub
  auth_token:
    secure: BRNTYGuumvD/xRHI/AuoKEKr1rzIXFm6TY5i+6wkD3dQKcKCgjJDJ7lZweoybafx
  artifact: deploy